language: ruby
script: bundle exec rspec
rvm:
- 2.7.0
deploy:
  provider: heroku
  api_key:
    secure: IgoAsoThwEwYwSo5Z2dd7utWSVX378vj2JZJ2Gl+e+bk/K7Lr60ZUy7PwUyOFOoYRF0X3x6Dbtfpr0CP1VDuASfPlEFJC5cA4eLQ36fo772jAMfFZhBY9WfRvKFJ81A/vYC5ogjnJ+cdkYSsxbINT88QgodRPlcuU3afG6+vR2mOToGmoVy+y8RrrGiv9hJwP1UeThVQd6ERnRE29JPVlylh6u2+zjIt022Iu6du9vHOCwe348uS92uxM0D41yCODtiC94mqKhnlQu8qsCjng95Z46tOPwkLUPi3w9mUH8Joh1vk75+rxp7Z41GTQXFb5n6U1Crbm7BHohvMherDhQ6knzzjOwMUyDv/rdlhqjuK/V3/cAPsL/wBVNbRoFsmmb+bfzC9UfrmGSUi9yQ26xE4s5YVvbWwbmPjpl6qFEbhKnSk5zxLnVnoqF8UW7BiKlfBrgbKUUINNO9uNyRwb4DBG38wYxZ+hep6WaNX/O6ADcBSrkoQ9CtakSS1Jsz+z95Cb9KqgALXZIzNfJCPgAquXoEFdT02mMWOz55gnL0G4aTzDOeDFpNkYpUNAvQS4RdFTabPB4so/ta4aKml30o76Kt74ROqkjg/WsmnYNgJbaL7gDkzld+ABHO+ZwFOApDg+ZbJQIYxIyHC16Y/RxzhyMLsZNtQzRtmX5Oj6tU=
before_install:
- gem install bundler
